### PR TITLE
envs/yocto: add lz4

### PR DESCRIPTION
**Pull request by minijackson**
Found that this was needed while using the `bitbake-layers` tool.

### CODE REVIEW

**Comment by minijackson** [comment]
Another note while I'm currently testing Yocto: the `BB_ENV_EXTRAWHITE` variable was renamed `BB_ENV_PASSTHROUGH_ADDITIONS` and `bitbake` refuses to build if it finds this variable. This means that we should set one variable or the other depending on the Yocto version? Or do we just change it and let people refer to old version of `nix-environments`?

**Comment by Mic92** [comment]
switching to `BB_ENV_PASSTHROUGH_ADDITIONS` sounds fine. The alternative would be to have both variables if this is possible.

**Comment by Mic92** [comment]
also see https://github.com/nix-community/nix-environments/pull/26/files

**Comment by minijackson** [comment]
oh, for some reason I didn't see that PR, let's close this one, then. Thanks!

**Comment by Mic92** [comment]
The other pr seems stalled, if you want to take it over, go for it.

**Pull request closed without merging**
